class TableLabels {
  static Map<String, String> android = {
    "osArch": "Architecture",
    "osName": "OS name",
    "osVersion": "OS version",
    "pathSeparator": "Path separator",
    "userDir": "User path",
    "userHome": "User home",
    "userName": "User name",
    "versionCodename": "Version codename",
    "versionIncremental": "Version incremental",
    "versionPreviewSdkInt": "Version preview SDK",
    "versionRelease": "Version release",
    "versionSdkInt": "Version SDK",
    "versionSecurityPatch": "Security patch",
    "javaClassPath": "Classpath",
    "javaHome": "Home path",
    "javaIoTmpdir": "IO tmp path",
    "javaLibraryPath": "Library path",
    "javaVendor": "Vendor",
    "javaVendorUrl": "Vendor URL",
    "javaSpecificationVersion": "Specification version",
    "javaSpecificationVendor": "Specification vendor",
    "javaSpecificationName": "Specification name",
    "javaVmVersion": "VM version",
    "javaVmVendor": "VM vendor",
    "javaVmName": "VM name",
    "javaVmSpecificationVersion": "VM specification version",
    "javaVmSpecificationVendor": "VM specification vendor",
    "javaVmSpecificationName": "VM specification name",
  };

  static Map<String, String> hardware = {
    "board": "Board",
    "bootloader": "Bootloader",
    "brand": "Brand",
    "device": "Device",
    "display": "Diaplay",
    "host": "Host name",
    "id": "ID",
    "manufacturer": "Manufacturer",
    "model": "Model",
    "product": "Product",
    "fingerprint": "Fingerprint",
    "hardware": "Hardware",
    "supportedAbis32": "32bit ABI",
    "supportedAbis64": "64bit ABI",
    "supportedAbis": "All ABI",
    "tags": "Tags",
    "time": "Time",
    "type": "Type",
    "user": "User name",
  };

  static Map<String, String> connection = {
    "mac": "MAC address",
    "ip": "IP address",
    "speed": "Speed",
    "frequency": "Frequency",
    "ssid": "SSID",
    "level": "Signal level",
    "type": "Connection type",
    "gateway": "Gateway",
    "dns1": "DNS 1",
    "dns2": "DNS 2",
    "hidden": "Hidden",
    "bssid": "BSSID"
  };
}
